# Generated by Django 4.1.6 on 2023-06-01 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='question',
            field=models.TextField(blank=True),
        ),
    ]
